fix 1.21.3 support
koca2000/NoteBlockAPI pull request #109
Opened 2024-11-07 23:53 UTC by DaJokni

in 1.21.3 spigot changed Sound from being an enum into being an Interface, this PR adds handling for that. also a small improvement to reduce repetition.

2024-11-08 10:18 UTC, koca2000 requested changes
Thank you for your PR and code improvements. However, see my comment about the `String` class.

2024-11-08 10:18 UTC, koca2000 commented on src/main/java/com/xxmicloxx/NoteBlockAPI/utils/CompatibilityUtils.java
> +		return sound.isEnum() ? sound : Sound.class;
The class in `sound` can also be a `String` and in that case this would not work correctly. It would be better to check if the `Sound.class` is an interface and then act accordingly.

2024-11-08 21:10 UTC, DaJokni commented on src/main/java/com/xxmicloxx/NoteBlockAPI/utils/CompatibilityUtils.java
> +		return sound.isEnum() ? sound : Sound.class;
pushed a change, couldn't exactly figure out how to do that without errors in one of the versions I was testing on so my solution is a bit alternate. do let me know if it seems good.

2024-11-11 15:54 UTC, DaJokni commented on src/main/java/com/xxmicloxx/NoteBlockAPI/utils/CompatibilityUtils.java
> +		return sound.isEnum() ? sound : Sound.class;
wasn't aware it could be that simple, I've addressed this now

2024-11-11 16:29 UTC, merged